#!/usr/bin/env python3
"""
Generate random ChaCha20-Poly1305 test vectors as VHDL constants.

Usage:
    python3 generate_test_vectors.py            # 10 vectors (default)
    python3 generate_test_vectors.py -n 5       # 5 vectors
    python3 generate_test_vectors.py -n 3 --output vectors.vhd

Output: VHDL constant declarations ready to paste into sim/tb_chacha20_top.vhd.
"""

import sys
import argparse
import os
import secrets
from typing import List, Tuple

try:
    from Crypto.Cipher import ChaCha20
    from Crypto.Hash  import Poly1305
except ImportError:
    sys.exit("PyCryptodome not found.  Install with:  pip install pycryptodome")


def _encrypt_and_tag(key: bytes, nonce: bytes, plaintext: bytes):
    """
    VHDL-compatible ChaCha20 + raw Poly1305 (no AEAD framing, no AAD, no lengths).
    Matches the VHDL poly1305_mac construction exactly.
    """
    # Encrypt: ChaCha20 with counter=1
    cc = ChaCha20.new(key=key, nonce=nonce)
    cc.seek(64)   # skip counter=0 block (64 bytes), start at counter=1
    ciphertext = cc.encrypt(plaintext)
    # Tag: raw Poly1305 over ciphertext; key derived via RFC 8439 §2.6 (counter=0)
    mac = Poly1305.new(key=key, cipher=ChaCha20, nonce=nonce)
    mac.update(ciphertext)
    tag = mac.digest()
    return ciphertext, tag


def generate_vector(index: int) -> Tuple[bytes, bytes, bytes, bytes, bytes]:
    """
    Generate one random test vector.
    Returns (key, nonce, plaintext, ciphertext, tag).
    Plaintext is always 64 bytes (one ChaCha20 block).
    Tag computed with raw Poly1305 to match VHDL poly1305_mac (no AEAD framing).
    """
    key       = secrets.token_bytes(32)
    nonce     = secrets.token_bytes(12)
    plaintext = secrets.token_bytes(64)
    ciphertext, tag = _encrypt_and_tag(key, nonce, plaintext)
    return key, nonce, plaintext, ciphertext, tag


def bytes_to_vhdl_hex(data: bytes, name: str, width_bits: int) -> str:
    """Format bytes as a VHDL std_logic_vector constant."""
    hex_str = data.hex().upper()
    return f'    constant {name} : std_logic_vector({width_bits - 1} downto 0) := x"{hex_str}";'


def format_vector(index: int, key: bytes, nonce: bytes,
                  plaintext: bytes, ciphertext: bytes, tag: bytes) -> str:
    """Return a VHDL comment block + constant declarations for one test vector."""
    n = index
    lines = [
        f"",
        f"    -- ---------------------------------------------------------------",
        f"    -- Test Vector {n}  (randomly generated by generate_test_vectors.py)",
        f"    -- ---------------------------------------------------------------",
        bytes_to_vhdl_hex(key,        f"TV{n}_KEY",        256),
        bytes_to_vhdl_hex(nonce,      f"TV{n}_NONCE",       96),
        bytes_to_vhdl_hex(plaintext,  f"TV{n}_PLAINTEXT",  512),
        bytes_to_vhdl_hex(ciphertext, f"TV{n}_CIPHERTEXT", 512),
        bytes_to_vhdl_hex(tag,        f"TV{n}_TAG",        128),
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate random ChaCha20-Poly1305 test vectors as VHDL constants")
    parser.add_argument("-n", "--count",  type=int, default=10,
                        help="Number of test vectors to generate (default: 10)")
    parser.add_argument("--output", metavar="FILE",
                        help="Write output to FILE instead of stdout")
    parser.add_argument("--rfc-first", action="store_true",
                        help="Prepend the RFC 8439 §2.4.2 vector as TV0")
    args = parser.parse_args()

    sections = []
    sections.append("-- Auto-generated test vectors for sim/tb_chacha20_top.vhd")
    sections.append("-- Paste into the constant declarations section of the testbench.")
    sections.append("-- Each vector: 256-bit key, 96-bit nonce, 512-bit plaintext,")
    sections.append("--              512-bit ciphertext, 128-bit Poly1305 tag.")
    sections.append("")

    start_index = 0
    if args.rfc_first:
        # RFC 8439 §2.4.2 vector — tag computed with raw Poly1305 (VHDL-compatible)
        rfc_key   = bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        rfc_nonce = bytes.fromhex("000000000000004a00000000")
        rfc_pt    = bytes(64)
        rfc_ct, rfc_tag = _encrypt_and_tag(rfc_key, rfc_nonce, rfc_pt)
        sections.append(format_vector(0, rfc_key, rfc_nonce, rfc_pt, rfc_ct, rfc_tag))
        start_index = 1

    for i in range(start_index, start_index + args.count):
        key, nonce, pt, ct, tag = generate_vector(i)
        sections.append(format_vector(i, key, nonce, pt, ct, tag))

    output = "\n".join(sections) + "\n"

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Wrote {args.count + (1 if args.rfc_first else 0)} vectors to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
